### PR TITLE
Tag search

### PR DESCRIPTION
**Pull request by knirirr**
This adds a feature but doesn't change the other functionality of everything else. 

Go to  https://deploy-preview-24--fairassist.netlify.app/researchfields.

### CODE REVIEW

**Comment by allysonlister** [comment]
Thanks for the update to netlify. I really like how it's working and all seems smooth to me, including user-defined tags

One oddity...
Plant Cell Biology takes me to 5-3-1-0
Adding domain Bioimaging (which I expect will take it to 0-0-0-0) gives 0-1-0-0, so interested, I click on view results, and there are 0 results. Do you know why this disparity occurs please?

Also, view results stays on the same page - please could you have it open in a new tab or new window?

**Comment by knirirr** [comment]
The results should now open on a new page. I've made the search box clearable as well.
As for the missing record mystery, I'm not able to replicate this either on the netlify build or my development machine. If it persists then it will involve looking at developer tools on your laptop to investigate further.

**Comment by allysonlister** [comment]
Thank you that is odd! I'll try the same query again next week on a couple of browsers and see what I get.

I've also sent it to Susanna for feedback, and while she's said a few things there have been no major comments, and I'd like to double check with her next week before adding them here, as I want to make sure I'm understanding her correctly.

**Comment by knirirr** [comment]
This is no longer necessary due to more work having been done in another branch. So, I'll close this.

**Pull request closed without merging**
