### PR TITLE
Spam users' policy selections. #119

### PR DESCRIPTION
**Pull request by knirirr**
This does exactly what's requested in #119. 
Whether that behaviour is desirable as it stands is another matter... ;-)

### CODE REVIEW

**Review by prakhyatox — APPROVED** [review]

**Comment by allysonlister** [comment]
When I select the policy shown below, it doesn't try to also add its parent policy, but allows me to carry on with 0 results and hasn't selected the parent policy for me....
image

Am I doing something wrong? I selected the cell cycle journal from T&F and it didn't add the parent policies...

**Comment by knirirr** [comment]
The system says that there are no parent policies to add. According to https://preview.fairsharing.org/5253, this is correct: 5253 extends one other policy itself but it is not extended by any policies.

**Comment by allysonlister** [comment]
There are two parent policies for https://fairsharing.org/5253

5253 extends 5467, which itself extends 3489

**Comment by knirirr** [comment]
> There are two parent policies for https://fairsharing.org/5253
> 
> 5253 extends 5467, which itself extends 3489

The're not on the development server. 
If you want to use those examples then I'll have to reload the database and reindex Elasticsearch and Neo4j, so the development API will go offline for a while.

**Comment by allysonlister** [comment]
Ah I get it! They are too new. No worries, I see you're doing an update now, let me know when it's done and I'll try again. Thanks!

**Comment by knirirr** [comment]
I've now restarted the server.
I was using Springer Nature policies during development which behaved as expected.

**Comment by allysonlister** [comment]
Thanks! So, it still seems to be 'backwards' to me? See the video below: when I select the child policy (Cell Cycle), none of the parents are chosen. However, when I choose one of the parent policies, all children are chosen....

Remember, that the 'extends' relationship looks like (example from https://fairsharing.org/5253):
image

So, because 5253 extends 5467 , which itself extends 3489 -> this means when I select 5253, both 5467 and 3489 should appear.

video:

[Screencast from 2024-07-04 11-28-49.webm](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/b712dc5e-0fcb-482d-b30c-1b4ea6c2d1e4)

**Comment by allysonlister** [comment]
Well, the way it looks is great, but I can't get the relationships to work properly at all, e.g. selecting 5263 does not automatically select 3449 so I'm struggling to get the behaviour I need to test.

Selecting 5119 (a parent policy,and therefore one that should NOT bring in any additional policies), I can see the behaviour. The way it looks is great, though the behaviour is wrong.

The links on the results page for using 5119 (the results page at https://deploy-preview-121--fairassist.netlify.app/results) don't work btw. clicking on Archaeology Data Service here:
image
loads https://fairsharing.org//FAIRsharing.hm1mfg (too many "/"?)

**Comment by knirirr** [comment]
Good to know that the general appearance is acceptable, despite an extraneous '/' which I will address here. I'll deal with the actual results in https://github.com/FAIRsharing/FAIRsharing-API/issues/1011.

**Comment by knirirr** [comment]
The '/' is due to the Netlify configuration here and doesn't affect production. I've changed it, but it may not be reflected in this build.

**Comment by allysonlister** [comment]
image
When I select a policy with no parents (Beilstein), then add in a policy that has parents (Cell Cycle), the parents of Cell Cycle are not included.

The screenshot mentions 109 records; that is a leftover that has _not_ cleared from a previous query; that may need a separate ticket - I believe my earlier query was eLife journal + Beilstein, for completeness.

**Comment by knirirr** [comment]
> When I select a policy with no parents (Beilstein), then add in a policy that has parents (Cell Cycle), the parents of Cell Cycle are not included.

The linked records for the second policy are not present in the neo4j database on the development server for reasons as yet unknown, but the code is working as it should. 

> The screenshot mentions 109 records; that is a leftover that has _not_ cleared from a previous query; that may need a separate ticket - I believe my earlier query was eLife journal + Beilstein, for completeness.

What steps did you follow between queries in order to produce this result?

**Comment by allysonlister** [comment]
FYI the 'second' policy (Cell Cycle?) does work correctly, so not sure why the graph appears not to show the connections?
image

Further, I'm not sure what happened yesterday as I try to repeat the issue and I can't; all is working as expected!

Anyway, I have tried multiple ways to break the new feature today and I can't, so all seems OK and I am approving. If the mystery issue crops up again I can make a new ticket.

**Review by allysonlister — APPROVED** [review]

**Comment by knirirr** [comment]
Thanks. I have rebuilt the graph since yesterday, and made another small fix.

**Pull request merged**
